### ISSUE TITLE
v3.3/glfw: update to latest GLFW release

### ISSUE THREAD

**Issue by dmitshur** [go-gl/glfw3#339]
There are new upstream GLFW releases available to be picked up:

- [GLFW 3.3.6](https://github.com/glfw/glfw/releases/tag/3.3.6) was released on [December 9, 2021](https://www.glfw.org/changelog.html).
- [GLFW 3.3.5](https://github.com/glfw/glfw/releases/tag/3.3.5) was released on [October 28, 2021](https://www.glfw.org/changelog.html).

`glfw` is currently using GLFW 3.3.4 and should be updated.

**Comment by Jacalz** [comment]
It is probably time to update to 3.3.6 now :)

https://www.glfw.org/changelog.html

**Comment by dmitshur** [comment]
Indeed. @Jacalz, if you'd like and are able to, please feel free to send a PR. The last update was in PR #329, and its commit message should have helpful information. Improvements to make the grab-upstream.sh script more robust and portable are welcome. Thanks!

**Comment by Jacalz** [comment]
Sure thing. Might give it a try :)

**Comment by Jacalz** [comment]
Alright. I have a PR open now. That went smoother than expected :)
