### ISSUE TITLE
GLFW is not installing "/usr/bin/ld: cannot find -lXxf86vm"

### ISSUE THREAD

**Issue by IsAmogusDead** [go-gl/glfw3#343]
i have been trying to install glfw for an entire night now and seeing how i have basically little to no knowledge in openGL or troubleshooting errors, it is an absolute nightmare. when i first try to install glfw i get this error
 `userk@fedora ~/Documents (master) [2]> go get github.com/go-gl/glfw/v3.3/glfw
github.com/go-gl/glfw/v3.3/glfw
/usr/bin/ld: cannot find -lXxf86vm
collect2: error: ld returned 1 exit status`
i have been searching through all the entries in the issues tab and have been searching every nook and cranny of the internet, but neither google nor duckduckgo give me any results.
sorry for any inconvinience i pose. i am very sorry.

**Comment by MonstraG** [comment]
Per https://github.com/go-gl/glfw/issues/286#issuecomment-654679135, install `libXxf86vm-devel`
