### ISSUE TITLE
Old module name in README installation instructions

### ISSUE THREAD

**Issue by fzipp** [go-gl/glfw3#369]
The README refers to the following module name in the installation instructions:

```
github.com/go-gl/glfw/v3.3/glfw
```

which is associated with [a go.mod file from 2019](https://github.com/go-gl/glfw/blob/93cebf72946bdd130bbda47817ad53315d776ca7/v3.3/glfw/go.mod), see the go.mod link [on pkg.go.dev](https://pkg.go.dev/github.com/go-gl/glfw/v3.3/glfw).

but the [current `go.mod` file](https://github.com/go-gl/glfw/blob/master/go.mod) in the repository declares this module name:

```
github.com/go-gl/glfw
```

**Comment by fzipp** [comment]
Weird, whenever I try to use the actual module name `github.com/go-gl/glfw` in my go.mod file, `go mod tidy` changes it back to `github.com/go-gl/glfw/v3.3/glfw`.

**Comment by dmitshur** [comment]
These are two different modules.

Module `github.com/go-gl/glfw/v3.3/glfw` (defined in `v3.3/glfw/go.mod`) contains v3.3.
Module `github.com/go-gl/glfw` (defined in `go.mod` file in repo root) contains older versions: v3.0, v3.1, and v3.2.

See https://go.dev/ref/mod#vcs-dir for more information about nested modules.

**Comment by fzipp** [comment]
Oh, there actually is a go.mod file in the subdirectory: https://github.com/go-gl/glfw/blob/master/v3.3/glfw/go.mod
Thanks, I'll close the issue.
