### ISSUE TITLE
How to use in windows?

### ISSUE THREAD

**Issue by everdrone** [go-gl/glfw3#374]
Is MSYS2 required when using `go 1.20`?

Trying to build the hello world program from `readme.md` gives the following errors:

```
.\main.go:16:14: undefined: glfw.Init
.\main.go:20:13: undefined: glfw.Terminate
.\main.go:22:22: undefined: glfw.CreateWindow
.\main.go:32:8: undefined: glfw.PollEvents
```

**Comment by Jacalz** [comment]
You will always need a C-compiler to build this package. I don't think it should be any difference using Go 1.20 as that always was the case. As Go doesn't yet support clang on Windows, I believe you need to use MSYS2 (or similar) and a suitable installation of GCC. The [docs for Fyne installation](https://developer.fyne.io/started/) on Windows should be able to help out with installing it as the dependencies are exactly the same.

Per the CGo section in the [Go 1.20 release notes](https://tip.golang.org/doc/go1.20), `CGO_ENABLED` will be disabled unless a C-compiler is installed. I don't think that should change anything here though as we don't have any precompiled C-headers as far as I'm aware.

**Comment by Jacalz** [comment]
I believe the above comment to answer your problem and will close this issues. Feel free to reopen if you don't agree.
