### ISSUE TITLE
Any way to try the glfw master branch to use libdecor ?

### ISSUE THREAD

**Issue by metal3d** [go-gl/glfw3#378]
Hello,

As we already discussed earlier for Fyne.io project, Wayland is badly supported at this time as the decoration should be made client side.

GLFW seems to now manage libdecor: 
https://github.com/glfw/glfw/blob/3eaf1255b29fdf5c2895856c7be7d7185ef2b241/docs/intro.dox#L166C6-L166C27

But, of course, there is no release from their repository to try this with Go :)

Have you got a manual to help me to test it with go-gl/glfw?

I know that you use some scripts to get/pull versions, but that not successful last time I tried.

A basic, TLDR would be appreciate ;)

Thanks a lot !

**Comment by Jacalz** [comment]
Glfw 3.3.9 includes libdecor support. This change has already landed in Fyne: https://github.com/fyne-io/fyne/pull/4481
