### ISSUE TITLE
scripts: Grab upstream fails to apply patch for v3.2

### ISSUE THREAD

**Issue by Jacalz** [go-gl/glfw3#397]
When updating `v3.3/glfw`, I have commented out the grabbing of upstream for `v3.2/glfw` because it fails to apply the patch. I looked into it a bit but didn't really know it behaves like that. It would be nice to have this fixed to make updates smoother. Or maybe v3.2 is dead in the water and we should just drop it from the script?

```
patching file README.md
Hunk #1 FAILED at 173.
1 out of 1 hunk FAILED
patching file src/x11_platform.h
Hunk #1 succeeded at 122 (offset -19 lines).
patching file src/x11_window.c
Hunk #1 succeeded at 993 (offset 1 line).
```

**Comment by dmitshur** [comment]
I think it's fine to leave v3.2 and older as is. I don't expect there will be new GLFW 3.2.x or older patch versions to update to. We should indeed update the script to focus on the current version (3.4.x now).
