### ISSUE TITLE
Vulkan: Loader not found

### ISSUE THREAD

**Issue by j0hnsmith** [go-gl/glfw3#403]
I'm trying to run a simple [hello world cogent example](https://github.com/cogentcore/core/blob/0fbbdd8f54e9cf0fd728c51345280fd0a3a3fa49/examples/basic/basic.go), it essentially runs this

https://github.com/cogentcore/core/blob/0fbbdd8f54e9cf0fd728c51345280fd0a3a3fa49/system/driver/desktop/app.go#L78-L85

```go 
	if err := glfw.Init(); err != nil {
		log.Fatalln("system/driver/desktop failed to initialize glfw:", err)
	}
	vk.SetGetInstanceProcAddr(glfw.GetVulkanGetInstanceProcAddress())
	vk.Init()
	glfw.SetMonitorCallback(a.MonitorChange)
	// glfw.DefaultWindowHints()
	glfw.WindowHint(glfw.ClientAPI, glfw.NoAPI)
```

But I get the error below

```
go-gl/glfw: internal error: an uncaught error has occurred: APIUnavailable: Vulkan: Loader not found
go-gl/glfw: Please report this in the Go package issue tracker.
go-gl/glfw: internal error: an uncaught error has occurred: APIUnavailable: Vulkan: Loader not found
go-gl/glfw: Please report this in the Go package issue tracker.
go-gl/glfw: internal error: an invalid error was not accepted by the caller: APIUnavailable: Vulkan: Loader not found
go-gl/glfw: Please report this in the Go package issue tracker.
panic: APIUnavailable: Vulkan: Loader not found

goroutine 1 [running, locked to thread]:
github.com/go-gl/glfw/v3.3/glfw.acceptError({0x0, 0x0, 0x1?})
        {redacted}/pkg/mod/github.com/go-gl/glfw/v3.3/glfw@v0.0.0-20240307211618-a69d953ea142/error.go:181 +0x214
github.com/go-gl/glfw/v3.3/glfw.panicError(...)
        {redacted}/pkg/mod/github.com/go-gl/glfw/v3.3/glfw@v0.0.0-20240307211618-a69d953ea142/error.go:188
github.com/go-gl/glfw/v3.3/glfw.WindowHint(0x10546bc88?, 0x104dba4a0?)
        {redacted}/pkg/mod/github.com/go-gl/glfw/v3.3/glfw@v0.0.0-20240307211618-a69d953ea142/window.go:274 +0x38
cogentcore.org/core/system/driver/desktop.(*App).InitVk(0x105f3f4c0)
        {redacted}/pkg/mod/cogentcore.org/core@v0.3.0/system/driver/desktop/app.go:85 +0xd0
cogentcore.org/core/system/driver/desktop.Init()
        {redacted}/pkg/mod/cogentcore.org/core@v0.3.0/system/driver/desktop/app.go:30 +0x28
cogentcore.org/core/system/driver.init.0()
        {redacted}/pkg/mod/cogentcore.org/core@v0.3.0/system/driver/driver_desktop.go:30 +0xcc
```

I've built and installed https://github.com/KhronosGroup/MoltenVK. The example from https://github.com/go-gl/glfw?tab=readme-ov-file#usage works. I've tried `go get -u -tags=vulkan github.com/go-gl/glfw/v3.3/glfw` but it didn't solve the problem. 

I'm using an arm mac. Any ideas how to solve the problem? Thanks

**Comment by dmitshur** [comment]
It sounds like Vulkan via MoltenVK on darwin/arm64 doesn’t work. It might not be supported.

Do you know if this is supported in the upstream GLFW C library? If it is, we should work on adding that support to this Go wrapper. Otherwise it would need to be added upstream first.

**Comment by j0hnsmith** [comment]
Not sure. The description for this [cogent demo video](https://www.youtube.com/watch?v=nZzdy3Kyypk) suggests that the example I'm trying should work (somehow?)

> Cogent Core  is a free and open source framework for building powerful, fast, elegant 2D and 3D apps that run on macOS, Windows, Linux, iOS, Android, and the web with a single Go (Golang) codebase, allowing you to Code Once, Run Everywhere.

**Comment by dmitshur** [comment]
Since you're running into this problem in the context of that project, I suggest you report an issue in that project's issue tracker, and reference this issue if needed.

**Comment by kkoreilly** [comment]
Vulkan via MoltenVK is supported on darwin/arm64, and everything should work correctly as long as `core setup` is run, which installs Vulkan correctly (see my comment on https://github.com/cogentcore/core/issues/1106).

**Comment by j0hnsmith** [comment]
I did, turns out I hadn't run an initial setup command, works now, thanks.
