### ISSUE TITLE
GLFW 3.3 missing functions like window attention

### ISSUE THREAD

**Issue by Aurora2500** [go-gl/glfw3#406]
There are some missing functions in this library that are present in the original one. For example [window attention](https://www.glfw.org/docs/3.3/window_guide.html#window_attention).

**Comment by dmitshur** [comment]
Some of the GLFW functions are methods in the Go bindings. For example, `void glfwRequestWindowAttention(GLFWwindow * window)` is [Window.RequestAttention](https://pkg.go.dev/github.com/go-gl/glfw/v3.3/glfw#Window.RequestAttention).

Is there something else specific that you see missing?

**Comment by Aurora2500** [comment]
guh, my bad. I haven't seen anything else as far that I thought to be missing.

Thanks!
